# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_Item', '0002_auto_20180220_1243'),
        ('_User', '0001_initial'),
        ('_Plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('plan_name', models.CharField(max_length=45)),
                ('share_flag', models.BooleanField()),
                ('start_datetime', models.DateField(auto_now_add=True)),
                ('end_datetime', models.DateField(auto_now_add=True)),
                ('end_address_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='end_time', to='_Plan.Address')),
                ('start_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_time', to='_Plan.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='plan_item',
            name='itemslot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Plan.TimeSlot'),
        ),
    ]
