# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 05:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_User', '0002_auto_20180219_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='_Plan.Item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='_Plan.Item'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star_point',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
