# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11 on 2018-02-19 12:40
=======
# Generated by Django 1.11 on 2018-02-20 11:59
>>>>>>> 77f9ab06c6220164bdd2d072a5a630e38d40069d
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('_Plan', '0001_initial'),
=======
>>>>>>> 77f9ab06c6220164bdd2d072a5a630e38d40069d
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('subtitle', models.TextField()),
                ('content', models.TextField()),
                ('main_img', models.ImageField(blank=True, upload_to='')),
                ('sub_img_1', models.ImageField(blank=True, upload_to='')),
                ('sub_img_2', models.ImageField(blank=True, upload_to='')),
                ('sub_img_3', models.ImageField(blank=True, upload_to='')),
                ('address', models.TextField()),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
<<<<<<< HEAD
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Plan.Category')),
=======
>>>>>>> 77f9ab06c6220164bdd2d072a5a630e38d40069d
            ],
        ),
        migrations.CreateModel(
            name='Item_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item_tag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Item.Tag'),
        ),
<<<<<<< HEAD
        migrations.AlterUniqueTogether(
            name='item_tag',
            unique_together=set([('item_id', 'tag_id')]),
        ),
=======
>>>>>>> 77f9ab06c6220164bdd2d072a5a630e38d40069d
    ]
