# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_User', '0001_initial'),
        ('_Item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_User.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='item_tag',
            unique_together=set([('item_id', 'tag_id')]),
        ),
    ]
